gamer
nirokay/Nimwit pull request #1
Opened 2023-09-05 17:39 UTC by FarToomMuchProgramming

what I like about you, do do do do we, we, we, we _Insert other lyrics from the cars movie here_

2023-09-05 17:39 UTC, FarToomMuchProgramming commented
I basically added some more terms to for the bot to look for, and added a helpful comment that niro should consider implementing in the future

2023-09-05 17:44 UTC, nirokay requested changes
sus

![image](https://github.com/nirokay/Nimwit/assets/80123634/2db10a3a-0ae8-49de-bcf9-5457aae5997d)

2023-09-05 17:50 UTC, FarToomMuchProgramming commented
ah ok, sorry niro, I added all the relevant changes you wanted me to, please dont fire me

2025-07-07 09:05 UTC, nirokay commented
CAT!!!!

2025-07-07 09:05 UTC, merged